### ISSUE TITLE
Auto startup using supervisor

### ISSUE THREAD

**Issue by sdndude** [PaloAltoNetworks/safe-networking-sp#26]
Current version of SFN requires running two different commands to get SFN and the associated UI portal up and running.
Need this to be automatically started at system start time with support for start/stop/restart and status if possible.

**Comment by dreshytnik** [comment]
Hi Eddie.

My 5 cents after 20 minutes tries. I did it in the following way:

1. Created bash script: /usr/local/bin/sfn.sh with the following content:

#!/bin/bash

cd  /home/dreshytnik/safe-networking-sp
source /home/dreshytnik/safe-networking-sp/env/bin/activate
python /home/dreshytnik/safe-networking-sp/sfn

2. Made file executable

chmod 777 /usr/local/bin/sfn.sh 

3. Created sfn.service: /etc/systemd/system/sfn.service with the following content:

[Unit]
Description="Safe Networking Service"

[Service]
ExecStartPre=/bin/sleep 60
#important to have delay before start, otherwise it doesn't work
ExecStart=/usr/local/bin/sfn.sh

[Install]
WantedBy=default.target

4. Activated service:

sudo chmod 664 /etc/systemd/system/sfn.service
sudo systemctl daemon-reload
sudo systemctl enable sfn.service
sudo systemctl start sfn.service
sudo systemctl status sfn.service

5. Stop the service if needed
 
sudo systemctl stop sfn.service

**Comment by sdndude** [comment]
Thanks @dreshytnik, I will test this myself and figure out a way for the install/setup script to determine where safe-networking-sp resides on the filesystem and have it automatically fill that part in.

**Comment by sdndude** [comment]
Startup script (sfn.sh) is created dynamically when we run the install/setup.sh file, as per the directions.  It will also create a systemd service, enable it and start it.  
Thanks to @dreshytnik for the help on this.  Took a little bit of tweaking, but his instructions in #26 were helpful.

**Comment by sdndude** [comment]
Added new documentation about the startup script and using the systemctl/service commands to run it. Also moved old documentation to a new heading for running the system in debug mode.
